spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/weather?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!
  jpa:
    show-sql: true # ????? ??? ??? ??? ??
    database: mysql
openweathermap:
  key: 371705b1d38c6b127e2080b5dc869432
logging:
  config: classpath:logback-spring.xml